node_name             "${chef-server-user}"
chef_server_url       "https://${chef-server-fqdn}/organizations/${organization}"
client_key            "./${chef-server-user}.pem"
cookbook_path         "./cookbooks"
trusted_certs_dir     ".chef/trusted_certs"
knife[:secret_file] = ".chef/encrypted_data_bag_secret"
